name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'


      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: eco-carver-465001-q0

      - name: Build and push Docker image
        run: |
          IMAGE="gcr.io/eco-carver-465001-q0/real-time-api-image"
          docker build -t $IMAGE .
          gcloud auth configure-docker
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE="gcr.io/eco-carver-465001-q0/real-time-api-image"
          gcloud run deploy cc-fraud-api \
            --image $IMAGE \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080 \
            --service-account github-deployer@eco-carver-465001-q0.iam.gserviceaccount.com \
